version: 2.1
workflows:
  build-test-deploy:
    jobs:
      - build:
          filters:
              branches:
                  only: main
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}
    steps:
      - checkout
      - run: gradle clean build
  test:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: gradle test
    

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            set -x
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a jobify-backend-prod web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a jobify-backend-prod web
