version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test
